#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probjectjianghan.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="project")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertuserGroup(userGroup instance);
    partial void UpdateuserGroup(userGroup instance);
    partial void DeleteuserGroup(userGroup instance);
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    partial void Insertbh_data(bh_data instance);
    partial void Updatebh_data(bh_data instance);
    partial void Deletebh_data(bh_data instance);
    partial void Insertctc_data(ctc_data instance);
    partial void Updatectc_data(ctc_data instance);
    partial void Deletectc_data(ctc_data instance);
    partial void Insertcc_bh(cc_bh instance);
    partial void Updatecc_bh(cc_bh instance);
    partial void Deletecc_bh(cc_bh instance);
    partial void Insertcc_ctc(cc_ctc instance);
    partial void Updatecc_ctc(cc_ctc instance);
    partial void Deletecc_ctc(cc_ctc instance);
    partial void Insertcatalog(catalog instance);
    partial void Updatecatalog(catalog instance);
    partial void Deletecatalog(catalog instance);
    #endregion
		
		public dbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["projectConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<userGroup> userGroup
		{
			get
			{
				return this.GetTable<userGroup>();
			}
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
		
		public System.Data.Linq.Table<bh_data> bh_data
		{
			get
			{
				return this.GetTable<bh_data>();
			}
		}
		
		public System.Data.Linq.Table<ctc_data> ctc_data
		{
			get
			{
				return this.GetTable<ctc_data>();
			}
		}
		
		public System.Data.Linq.Table<cc_bh> cc_bh
		{
			get
			{
				return this.GetTable<cc_bh>();
			}
		}
		
		public System.Data.Linq.Table<cc_ctc> cc_ctc
		{
			get
			{
				return this.GetTable<cc_ctc>();
			}
		}
		
		public System.Data.Linq.Table<catalog> catalog
		{
			get
			{
				return this.GetTable<catalog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userGroup")]
	public partial class userGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _groupID;
		
		private string _groupName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngroupIDChanging(int value);
    partial void OngroupIDChanged();
    partial void OngroupNameChanging(string value);
    partial void OngroupNameChanged();
    #endregion
		
		public userGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int groupID
		{
			get
			{
				return this._groupID;
			}
			set
			{
				if ((this._groupID != value))
				{
					this.OngroupIDChanging(value);
					this.SendPropertyChanging();
					this._groupID = value;
					this.SendPropertyChanged("groupID");
					this.OngroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string groupName
		{
			get
			{
				return this._groupName;
			}
			set
			{
				if ((this._groupName != value))
				{
					this.OngroupNameChanging(value);
					this.SendPropertyChanging();
					this._groupName = value;
					this.SendPropertyChanged("groupName");
					this.OngroupNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userID;
		
		private string _userAccount;
		
		private string _userPwd;
		
		private string _userName;
		
		private System.Nullable<int> _userState;
		
		private int _groupID;
		
		private System.Nullable<System.DateTime> _lastLoginTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(int value);
    partial void OnuserIDChanged();
    partial void OnuserAccountChanging(string value);
    partial void OnuserAccountChanged();
    partial void OnuserPwdChanging(string value);
    partial void OnuserPwdChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnuserStateChanging(System.Nullable<int> value);
    partial void OnuserStateChanged();
    partial void OngroupIDChanging(int value);
    partial void OngroupIDChanged();
    partial void OnlastLoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastLoginTimeChanged();
    #endregion
		
		public users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userAccount", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string userAccount
		{
			get
			{
				return this._userAccount;
			}
			set
			{
				if ((this._userAccount != value))
				{
					this.OnuserAccountChanging(value);
					this.SendPropertyChanging();
					this._userAccount = value;
					this.SendPropertyChanged("userAccount");
					this.OnuserAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPwd", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string userPwd
		{
			get
			{
				return this._userPwd;
			}
			set
			{
				if ((this._userPwd != value))
				{
					this.OnuserPwdChanging(value);
					this.SendPropertyChanging();
					this._userPwd = value;
					this.SendPropertyChanged("userPwd");
					this.OnuserPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userState", DbType="Int")]
		public System.Nullable<int> userState
		{
			get
			{
				return this._userState;
			}
			set
			{
				if ((this._userState != value))
				{
					this.OnuserStateChanging(value);
					this.SendPropertyChanging();
					this._userState = value;
					this.SendPropertyChanged("userState");
					this.OnuserStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupID", DbType="Int NOT NULL")]
		public int groupID
		{
			get
			{
				return this._groupID;
			}
			set
			{
				if ((this._groupID != value))
				{
					this.OngroupIDChanging(value);
					this.SendPropertyChanging();
					this._groupID = value;
					this.SendPropertyChanged("groupID");
					this.OngroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLoginTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastLoginTime
		{
			get
			{
				return this._lastLoginTime;
			}
			set
			{
				if ((this._lastLoginTime != value))
				{
					this.OnlastLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._lastLoginTime = value;
					this.SendPropertyChanged("lastLoginTime");
					this.OnlastLoginTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bh_data")]
	public partial class bh_data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _nbigarea;
		
		private System.Nullable<int> _nsmallarea;
		
		private string _type;
		
		private string _sn;
		
		private System.Nullable<double> _pcl;
		
		private System.Nullable<double> _pcr;
		
		private string _ls;
		
		private System.Nullable<double> _cwl;
		
		private System.Nullable<double> _cwr;
		
		private System.Nullable<double> _mh;
		
		private string _mtl1;
		
		private string _mtr1;
		
		private string _rtl1;
		
		private string _rtr1;
		
		private string _sdtl;
		
		private string _olt;
		
		private string _mln;
		
		private string _cbd;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnbigareaChanging(System.Nullable<int> value);
    partial void OnnbigareaChanged();
    partial void OnnsmallareaChanging(System.Nullable<int> value);
    partial void OnnsmallareaChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnsnChanging(string value);
    partial void OnsnChanged();
    partial void OnpclChanging(System.Nullable<double> value);
    partial void OnpclChanged();
    partial void OnpcrChanging(System.Nullable<double> value);
    partial void OnpcrChanged();
    partial void OnlsChanging(string value);
    partial void OnlsChanged();
    partial void OncwlChanging(System.Nullable<double> value);
    partial void OncwlChanged();
    partial void OncwrChanging(System.Nullable<double> value);
    partial void OncwrChanged();
    partial void OnmhChanging(System.Nullable<double> value);
    partial void OnmhChanged();
    partial void Onmtl1Changing(string value);
    partial void Onmtl1Changed();
    partial void Onmtr1Changing(string value);
    partial void Onmtr1Changed();
    partial void Onrtl1Changing(string value);
    partial void Onrtl1Changed();
    partial void Onrtr1Changing(string value);
    partial void Onrtr1Changed();
    partial void OnsdtlChanging(string value);
    partial void OnsdtlChanged();
    partial void OnoltChanging(string value);
    partial void OnoltChanged();
    partial void OnmlnChanging(string value);
    partial void OnmlnChanged();
    partial void OncbdChanging(string value);
    partial void OncbdChanged();
    #endregion
		
		public bh_data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbigarea", DbType="Int")]
		public System.Nullable<int> nbigarea
		{
			get
			{
				return this._nbigarea;
			}
			set
			{
				if ((this._nbigarea != value))
				{
					this.OnnbigareaChanging(value);
					this.SendPropertyChanging();
					this._nbigarea = value;
					this.SendPropertyChanged("nbigarea");
					this.OnnbigareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsmallarea", DbType="Int")]
		public System.Nullable<int> nsmallarea
		{
			get
			{
				return this._nsmallarea;
			}
			set
			{
				if ((this._nsmallarea != value))
				{
					this.OnnsmallareaChanging(value);
					this.SendPropertyChanging();
					this._nsmallarea = value;
					this.SendPropertyChanged("nsmallarea");
					this.OnnsmallareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(255)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn", DbType="NVarChar(255)")]
		public string sn
		{
			get
			{
				return this._sn;
			}
			set
			{
				if ((this._sn != value))
				{
					this.OnsnChanging(value);
					this.SendPropertyChanging();
					this._sn = value;
					this.SendPropertyChanged("sn");
					this.OnsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcl", DbType="Float")]
		public System.Nullable<double> pcl
		{
			get
			{
				return this._pcl;
			}
			set
			{
				if ((this._pcl != value))
				{
					this.OnpclChanging(value);
					this.SendPropertyChanging();
					this._pcl = value;
					this.SendPropertyChanged("pcl");
					this.OnpclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcr", DbType="Float")]
		public System.Nullable<double> pcr
		{
			get
			{
				return this._pcr;
			}
			set
			{
				if ((this._pcr != value))
				{
					this.OnpcrChanging(value);
					this.SendPropertyChanging();
					this._pcr = value;
					this.SendPropertyChanged("pcr");
					this.OnpcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ls", DbType="NVarChar(255)")]
		public string ls
		{
			get
			{
				return this._ls;
			}
			set
			{
				if ((this._ls != value))
				{
					this.OnlsChanging(value);
					this.SendPropertyChanging();
					this._ls = value;
					this.SendPropertyChanged("ls");
					this.OnlsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cwl", DbType="Float")]
		public System.Nullable<double> cwl
		{
			get
			{
				return this._cwl;
			}
			set
			{
				if ((this._cwl != value))
				{
					this.OncwlChanging(value);
					this.SendPropertyChanging();
					this._cwl = value;
					this.SendPropertyChanged("cwl");
					this.OncwlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cwr", DbType="Float")]
		public System.Nullable<double> cwr
		{
			get
			{
				return this._cwr;
			}
			set
			{
				if ((this._cwr != value))
				{
					this.OncwrChanging(value);
					this.SendPropertyChanging();
					this._cwr = value;
					this.SendPropertyChanged("cwr");
					this.OncwrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mh", DbType="Float")]
		public System.Nullable<double> mh
		{
			get
			{
				return this._mh;
			}
			set
			{
				if ((this._mh != value))
				{
					this.OnmhChanging(value);
					this.SendPropertyChanging();
					this._mh = value;
					this.SendPropertyChanged("mh");
					this.OnmhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtl1", DbType="NVarChar(255)")]
		public string mtl1
		{
			get
			{
				return this._mtl1;
			}
			set
			{
				if ((this._mtl1 != value))
				{
					this.Onmtl1Changing(value);
					this.SendPropertyChanging();
					this._mtl1 = value;
					this.SendPropertyChanged("mtl1");
					this.Onmtl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtr1", DbType="NVarChar(255)")]
		public string mtr1
		{
			get
			{
				return this._mtr1;
			}
			set
			{
				if ((this._mtr1 != value))
				{
					this.Onmtr1Changing(value);
					this.SendPropertyChanging();
					this._mtr1 = value;
					this.SendPropertyChanged("mtr1");
					this.Onmtr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtl1", DbType="NVarChar(255)")]
		public string rtl1
		{
			get
			{
				return this._rtl1;
			}
			set
			{
				if ((this._rtl1 != value))
				{
					this.Onrtl1Changing(value);
					this.SendPropertyChanging();
					this._rtl1 = value;
					this.SendPropertyChanged("rtl1");
					this.Onrtl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtr1", DbType="NVarChar(255)")]
		public string rtr1
		{
			get
			{
				return this._rtr1;
			}
			set
			{
				if ((this._rtr1 != value))
				{
					this.Onrtr1Changing(value);
					this.SendPropertyChanging();
					this._rtr1 = value;
					this.SendPropertyChanged("rtr1");
					this.Onrtr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtl", DbType="NVarChar(255)")]
		public string sdtl
		{
			get
			{
				return this._sdtl;
			}
			set
			{
				if ((this._sdtl != value))
				{
					this.OnsdtlChanging(value);
					this.SendPropertyChanging();
					this._sdtl = value;
					this.SendPropertyChanged("sdtl");
					this.OnsdtlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_olt", DbType="NVarChar(255)")]
		public string olt
		{
			get
			{
				return this._olt;
			}
			set
			{
				if ((this._olt != value))
				{
					this.OnoltChanging(value);
					this.SendPropertyChanging();
					this._olt = value;
					this.SendPropertyChanged("olt");
					this.OnoltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mln", DbType="NVarChar(50)")]
		public string mln
		{
			get
			{
				return this._mln;
			}
			set
			{
				if ((this._mln != value))
				{
					this.OnmlnChanging(value);
					this.SendPropertyChanging();
					this._mln = value;
					this.SendPropertyChanged("mln");
					this.OnmlnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbd", DbType="NVarChar(50)")]
		public string cbd
		{
			get
			{
				return this._cbd;
			}
			set
			{
				if ((this._cbd != value))
				{
					this.OncbdChanging(value);
					this.SendPropertyChanging();
					this._cbd = value;
					this.SendPropertyChanged("cbd");
					this.OncbdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ctc_data")]
	public partial class ctc_data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _nbigarea;
		
		private System.Nullable<int> _nsmallarea;
		
		private string _type;
		
		private string _sn;
		
		private string _pc;
		
		private System.Nullable<double> _rhm;
		
		private System.Nullable<double> _mhc;
		
		private System.Nullable<double> _mrc;
		
		private string _minmaxwr;
		
		private string _cbw;
		
		private System.Nullable<double> _cjbw;
		
		private System.Nullable<double> _sh;
		
		private System.Nullable<double> _maxah;
		
		private string _hs;
		
		private string _ts;
		
		private string _ss;
		
		private System.Nullable<double> _cw;
		
		private string _mln;
		
		private string _hwt;
		
		private string _twt;
		
		private string _sgt;
		
		private string _cmt;
		
		private string _hr;
		
		private string _lcot;
		
		private string _mcot;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnbigareaChanging(System.Nullable<int> value);
    partial void OnnbigareaChanged();
    partial void OnnsmallareaChanging(System.Nullable<int> value);
    partial void OnnsmallareaChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnsnChanging(string value);
    partial void OnsnChanged();
    partial void OnpcChanging(string value);
    partial void OnpcChanged();
    partial void OnrhmChanging(System.Nullable<double> value);
    partial void OnrhmChanged();
    partial void OnmhcChanging(System.Nullable<double> value);
    partial void OnmhcChanged();
    partial void OnmrcChanging(System.Nullable<double> value);
    partial void OnmrcChanged();
    partial void OnminmaxwrChanging(string value);
    partial void OnminmaxwrChanged();
    partial void OncbwChanging(string value);
    partial void OncbwChanged();
    partial void OncjbwChanging(System.Nullable<double> value);
    partial void OncjbwChanged();
    partial void OnshChanging(System.Nullable<double> value);
    partial void OnshChanged();
    partial void OnmaxahChanging(System.Nullable<double> value);
    partial void OnmaxahChanged();
    partial void OnhsChanging(string value);
    partial void OnhsChanged();
    partial void OntsChanging(string value);
    partial void OntsChanged();
    partial void OnssChanging(string value);
    partial void OnssChanged();
    partial void OncwChanging(System.Nullable<double> value);
    partial void OncwChanged();
    partial void OnmlnChanging(string value);
    partial void OnmlnChanged();
    partial void OnhwtChanging(string value);
    partial void OnhwtChanged();
    partial void OntwtChanging(string value);
    partial void OntwtChanged();
    partial void OnsgtChanging(string value);
    partial void OnsgtChanged();
    partial void OncmtChanging(string value);
    partial void OncmtChanged();
    partial void OnhrChanging(string value);
    partial void OnhrChanged();
    partial void OnlcotChanging(string value);
    partial void OnlcotChanged();
    partial void OnmcotChanging(string value);
    partial void OnmcotChanged();
    #endregion
		
		public ctc_data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbigarea", DbType="Int")]
		public System.Nullable<int> nbigarea
		{
			get
			{
				return this._nbigarea;
			}
			set
			{
				if ((this._nbigarea != value))
				{
					this.OnnbigareaChanging(value);
					this.SendPropertyChanging();
					this._nbigarea = value;
					this.SendPropertyChanged("nbigarea");
					this.OnnbigareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nsmallarea", DbType="Int")]
		public System.Nullable<int> nsmallarea
		{
			get
			{
				return this._nsmallarea;
			}
			set
			{
				if ((this._nsmallarea != value))
				{
					this.OnnsmallareaChanging(value);
					this.SendPropertyChanging();
					this._nsmallarea = value;
					this.SendPropertyChanged("nsmallarea");
					this.OnnsmallareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(255)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn", DbType="NVarChar(255)")]
		public string sn
		{
			get
			{
				return this._sn;
			}
			set
			{
				if ((this._sn != value))
				{
					this.OnsnChanging(value);
					this.SendPropertyChanging();
					this._sn = value;
					this.SendPropertyChanged("sn");
					this.OnsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pc", DbType="NVarChar(255)")]
		public string pc
		{
			get
			{
				return this._pc;
			}
			set
			{
				if ((this._pc != value))
				{
					this.OnpcChanging(value);
					this.SendPropertyChanging();
					this._pc = value;
					this.SendPropertyChanged("pc");
					this.OnpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rhm", DbType="Float")]
		public System.Nullable<double> rhm
		{
			get
			{
				return this._rhm;
			}
			set
			{
				if ((this._rhm != value))
				{
					this.OnrhmChanging(value);
					this.SendPropertyChanging();
					this._rhm = value;
					this.SendPropertyChanged("rhm");
					this.OnrhmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mhc", DbType="Float")]
		public System.Nullable<double> mhc
		{
			get
			{
				return this._mhc;
			}
			set
			{
				if ((this._mhc != value))
				{
					this.OnmhcChanging(value);
					this.SendPropertyChanging();
					this._mhc = value;
					this.SendPropertyChanged("mhc");
					this.OnmhcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mrc", DbType="Float")]
		public System.Nullable<double> mrc
		{
			get
			{
				return this._mrc;
			}
			set
			{
				if ((this._mrc != value))
				{
					this.OnmrcChanging(value);
					this.SendPropertyChanging();
					this._mrc = value;
					this.SendPropertyChanged("mrc");
					this.OnmrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minmaxwr", DbType="NVarChar(255)")]
		public string minmaxwr
		{
			get
			{
				return this._minmaxwr;
			}
			set
			{
				if ((this._minmaxwr != value))
				{
					this.OnminmaxwrChanging(value);
					this.SendPropertyChanging();
					this._minmaxwr = value;
					this.SendPropertyChanged("minmaxwr");
					this.OnminmaxwrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbw", DbType="NVarChar(255)")]
		public string cbw
		{
			get
			{
				return this._cbw;
			}
			set
			{
				if ((this._cbw != value))
				{
					this.OncbwChanging(value);
					this.SendPropertyChanging();
					this._cbw = value;
					this.SendPropertyChanged("cbw");
					this.OncbwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cjbw", DbType="Float")]
		public System.Nullable<double> cjbw
		{
			get
			{
				return this._cjbw;
			}
			set
			{
				if ((this._cjbw != value))
				{
					this.OncjbwChanging(value);
					this.SendPropertyChanging();
					this._cjbw = value;
					this.SendPropertyChanged("cjbw");
					this.OncjbwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh", DbType="Float")]
		public System.Nullable<double> sh
		{
			get
			{
				return this._sh;
			}
			set
			{
				if ((this._sh != value))
				{
					this.OnshChanging(value);
					this.SendPropertyChanging();
					this._sh = value;
					this.SendPropertyChanged("sh");
					this.OnshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxah", DbType="Float")]
		public System.Nullable<double> maxah
		{
			get
			{
				return this._maxah;
			}
			set
			{
				if ((this._maxah != value))
				{
					this.OnmaxahChanging(value);
					this.SendPropertyChanging();
					this._maxah = value;
					this.SendPropertyChanged("maxah");
					this.OnmaxahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hs", DbType="NVarChar(255)")]
		public string hs
		{
			get
			{
				return this._hs;
			}
			set
			{
				if ((this._hs != value))
				{
					this.OnhsChanging(value);
					this.SendPropertyChanging();
					this._hs = value;
					this.SendPropertyChanged("hs");
					this.OnhsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="NVarChar(255)")]
		public string ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss", DbType="NVarChar(255)")]
		public string ss
		{
			get
			{
				return this._ss;
			}
			set
			{
				if ((this._ss != value))
				{
					this.OnssChanging(value);
					this.SendPropertyChanging();
					this._ss = value;
					this.SendPropertyChanged("ss");
					this.OnssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cw", DbType="Float")]
		public System.Nullable<double> cw
		{
			get
			{
				return this._cw;
			}
			set
			{
				if ((this._cw != value))
				{
					this.OncwChanging(value);
					this.SendPropertyChanging();
					this._cw = value;
					this.SendPropertyChanged("cw");
					this.OncwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mln", DbType="NVarChar(50)")]
		public string mln
		{
			get
			{
				return this._mln;
			}
			set
			{
				if ((this._mln != value))
				{
					this.OnmlnChanging(value);
					this.SendPropertyChanging();
					this._mln = value;
					this.SendPropertyChanged("mln");
					this.OnmlnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hwt", DbType="NVarChar(200)")]
		public string hwt
		{
			get
			{
				return this._hwt;
			}
			set
			{
				if ((this._hwt != value))
				{
					this.OnhwtChanging(value);
					this.SendPropertyChanging();
					this._hwt = value;
					this.SendPropertyChanged("hwt");
					this.OnhwtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twt", DbType="NVarChar(200)")]
		public string twt
		{
			get
			{
				return this._twt;
			}
			set
			{
				if ((this._twt != value))
				{
					this.OntwtChanging(value);
					this.SendPropertyChanging();
					this._twt = value;
					this.SendPropertyChanged("twt");
					this.OntwtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sgt", DbType="NVarChar(200)")]
		public string sgt
		{
			get
			{
				return this._sgt;
			}
			set
			{
				if ((this._sgt != value))
				{
					this.OnsgtChanging(value);
					this.SendPropertyChanging();
					this._sgt = value;
					this.SendPropertyChanged("sgt");
					this.OnsgtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmt", DbType="NVarChar(200)")]
		public string cmt
		{
			get
			{
				return this._cmt;
			}
			set
			{
				if ((this._cmt != value))
				{
					this.OncmtChanging(value);
					this.SendPropertyChanging();
					this._cmt = value;
					this.SendPropertyChanged("cmt");
					this.OncmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr", DbType="NVarChar(200)")]
		public string hr
		{
			get
			{
				return this._hr;
			}
			set
			{
				if ((this._hr != value))
				{
					this.OnhrChanging(value);
					this.SendPropertyChanging();
					this._hr = value;
					this.SendPropertyChanged("hr");
					this.OnhrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lcot", DbType="NVarChar(200)")]
		public string lcot
		{
			get
			{
				return this._lcot;
			}
			set
			{
				if ((this._lcot != value))
				{
					this.OnlcotChanging(value);
					this.SendPropertyChanging();
					this._lcot = value;
					this.SendPropertyChanged("lcot");
					this.OnlcotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mcot", DbType="NVarChar(200)")]
		public string mcot
		{
			get
			{
				return this._mcot;
			}
			set
			{
				if ((this._mcot != value))
				{
					this.OnmcotChanging(value);
					this.SendPropertyChanging();
					this._mcot = value;
					this.SendPropertyChanged("mcot");
					this.OnmcotChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cc_bh")]
	public partial class cc_bh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _uname;
		
		private string _ContractNO;
		
		private System.Nullable<System.DateTime> _fhtime;
		
		private System.Nullable<int> _fy;
		
		private System.Nullable<int> _fm;
		
		private System.Nullable<int> _fd;
		
		private string _mln;
		
		private string _name;
		
		private string _type;
		
		private string _sn;
		
		private string _pn;
		
		private string _pc;
		
		private string _pcl;
		
		private string _pcr;
		
		private string _ls;
		
		private string _cwl;
		
		private string _cwr;
		
		private string _mh;
		
		private string _mtl1;
		
		private string _mtl2;
		
		private string _mtl3;
		
		private string _mtr1;
		
		private string _mtr2;
		
		private string _mtr3;
		
		private string _mnl1;
		
		private string _mnl2;
		
		private string _mnl3;
		
		private string _mnr1;
		
		private string _mnr2;
		
		private string _mnr3;
		
		private string _rtl1;
		
		private string _rtl2;
		
		private string _rtl3;
		
		private string _rnl1;
		
		private string _rnl2;
		
		private string _rnl3;
		
		private string _rtr1;
		
		private string _rtr2;
		
		private string _rtr3;
		
		private string _rnr1;
		
		private string _rnr2;
		
		private string _rnr3;
		
		private string _sdtl;
		
		private string _sdtr;
		
		private string _sdnl;
		
		private string _sdnr;
		
		private string _olt;
		
		private string _oln;
		
		private string _oln2;
		
		private string _sp1;
		
		private string _sp2;
		
		private string _y;
		
		private string _m;
		
		private string _d;
		
		private string _cbd;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OnContractNOChanging(string value);
    partial void OnContractNOChanged();
    partial void OnfhtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnfhtimeChanged();
    partial void OnfyChanging(System.Nullable<int> value);
    partial void OnfyChanged();
    partial void OnfmChanging(System.Nullable<int> value);
    partial void OnfmChanged();
    partial void OnfdChanging(System.Nullable<int> value);
    partial void OnfdChanged();
    partial void OnmlnChanging(string value);
    partial void OnmlnChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnsnChanging(string value);
    partial void OnsnChanged();
    partial void OnpnChanging(string value);
    partial void OnpnChanged();
    partial void OnpcChanging(string value);
    partial void OnpcChanged();
    partial void OnpclChanging(string value);
    partial void OnpclChanged();
    partial void OnpcrChanging(string value);
    partial void OnpcrChanged();
    partial void OnlsChanging(string value);
    partial void OnlsChanged();
    partial void OncwlChanging(string value);
    partial void OncwlChanged();
    partial void OncwrChanging(string value);
    partial void OncwrChanged();
    partial void OnmhChanging(string value);
    partial void OnmhChanged();
    partial void Onmtl1Changing(string value);
    partial void Onmtl1Changed();
    partial void Onmtl2Changing(string value);
    partial void Onmtl2Changed();
    partial void Onmtl3Changing(string value);
    partial void Onmtl3Changed();
    partial void Onmtr1Changing(string value);
    partial void Onmtr1Changed();
    partial void Onmtr2Changing(string value);
    partial void Onmtr2Changed();
    partial void Onmtr3Changing(string value);
    partial void Onmtr3Changed();
    partial void Onmnl1Changing(string value);
    partial void Onmnl1Changed();
    partial void Onmnl2Changing(string value);
    partial void Onmnl2Changed();
    partial void Onmnl3Changing(string value);
    partial void Onmnl3Changed();
    partial void Onmnr1Changing(string value);
    partial void Onmnr1Changed();
    partial void Onmnr2Changing(string value);
    partial void Onmnr2Changed();
    partial void Onmnr3Changing(string value);
    partial void Onmnr3Changed();
    partial void Onrtl1Changing(string value);
    partial void Onrtl1Changed();
    partial void Onrtl2Changing(string value);
    partial void Onrtl2Changed();
    partial void Onrtl3Changing(string value);
    partial void Onrtl3Changed();
    partial void Onrnl1Changing(string value);
    partial void Onrnl1Changed();
    partial void Onrnl2Changing(string value);
    partial void Onrnl2Changed();
    partial void Onrnl3Changing(string value);
    partial void Onrnl3Changed();
    partial void Onrtr1Changing(string value);
    partial void Onrtr1Changed();
    partial void Onrtr2Changing(string value);
    partial void Onrtr2Changed();
    partial void Onrtr3Changing(string value);
    partial void Onrtr3Changed();
    partial void Onrnr1Changing(string value);
    partial void Onrnr1Changed();
    partial void Onrnr2Changing(string value);
    partial void Onrnr2Changed();
    partial void Onrnr3Changing(string value);
    partial void Onrnr3Changed();
    partial void OnsdtlChanging(string value);
    partial void OnsdtlChanged();
    partial void OnsdtrChanging(string value);
    partial void OnsdtrChanged();
    partial void OnsdnlChanging(string value);
    partial void OnsdnlChanged();
    partial void OnsdnrChanging(string value);
    partial void OnsdnrChanged();
    partial void OnoltChanging(string value);
    partial void OnoltChanged();
    partial void OnolnChanging(string value);
    partial void OnolnChanged();
    partial void Onoln2Changing(string value);
    partial void Onoln2Changed();
    partial void Onsp1Changing(string value);
    partial void Onsp1Changed();
    partial void Onsp2Changing(string value);
    partial void Onsp2Changed();
    partial void OnyChanging(string value);
    partial void OnyChanged();
    partial void OnmChanging(string value);
    partial void OnmChanged();
    partial void OndChanging(string value);
    partial void OndChanged();
    partial void OncbdChanging(string value);
    partial void OncbdChanged();
    #endregion
		
		public cc_bh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="NVarChar(50)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this.OnunameChanging(value);
					this.SendPropertyChanging();
					this._uname = value;
					this.SendPropertyChanged("uname");
					this.OnunameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNO", DbType="NVarChar(50)")]
		public string ContractNO
		{
			get
			{
				return this._ContractNO;
			}
			set
			{
				if ((this._ContractNO != value))
				{
					this.OnContractNOChanging(value);
					this.SendPropertyChanging();
					this._ContractNO = value;
					this.SendPropertyChanged("ContractNO");
					this.OnContractNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fhtime", DbType="Date")]
		public System.Nullable<System.DateTime> fhtime
		{
			get
			{
				return this._fhtime;
			}
			set
			{
				if ((this._fhtime != value))
				{
					this.OnfhtimeChanging(value);
					this.SendPropertyChanging();
					this._fhtime = value;
					this.SendPropertyChanged("fhtime");
					this.OnfhtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fy", DbType="Int")]
		public System.Nullable<int> fy
		{
			get
			{
				return this._fy;
			}
			set
			{
				if ((this._fy != value))
				{
					this.OnfyChanging(value);
					this.SendPropertyChanging();
					this._fy = value;
					this.SendPropertyChanged("fy");
					this.OnfyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fm", DbType="Int")]
		public System.Nullable<int> fm
		{
			get
			{
				return this._fm;
			}
			set
			{
				if ((this._fm != value))
				{
					this.OnfmChanging(value);
					this.SendPropertyChanging();
					this._fm = value;
					this.SendPropertyChanged("fm");
					this.OnfmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd", DbType="Int")]
		public System.Nullable<int> fd
		{
			get
			{
				return this._fd;
			}
			set
			{
				if ((this._fd != value))
				{
					this.OnfdChanging(value);
					this.SendPropertyChanging();
					this._fd = value;
					this.SendPropertyChanged("fd");
					this.OnfdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mln", DbType="NVarChar(50)")]
		public string mln
		{
			get
			{
				return this._mln;
			}
			set
			{
				if ((this._mln != value))
				{
					this.OnmlnChanging(value);
					this.SendPropertyChanging();
					this._mln = value;
					this.SendPropertyChanged("mln");
					this.OnmlnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn", DbType="NVarChar(50)")]
		public string sn
		{
			get
			{
				return this._sn;
			}
			set
			{
				if ((this._sn != value))
				{
					this.OnsnChanging(value);
					this.SendPropertyChanging();
					this._sn = value;
					this.SendPropertyChanged("sn");
					this.OnsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pn", DbType="NVarChar(50)")]
		public string pn
		{
			get
			{
				return this._pn;
			}
			set
			{
				if ((this._pn != value))
				{
					this.OnpnChanging(value);
					this.SendPropertyChanging();
					this._pn = value;
					this.SendPropertyChanged("pn");
					this.OnpnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pc", DbType="NVarChar(50)")]
		public string pc
		{
			get
			{
				return this._pc;
			}
			set
			{
				if ((this._pc != value))
				{
					this.OnpcChanging(value);
					this.SendPropertyChanging();
					this._pc = value;
					this.SendPropertyChanged("pc");
					this.OnpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcl", DbType="NVarChar(50)")]
		public string pcl
		{
			get
			{
				return this._pcl;
			}
			set
			{
				if ((this._pcl != value))
				{
					this.OnpclChanging(value);
					this.SendPropertyChanging();
					this._pcl = value;
					this.SendPropertyChanged("pcl");
					this.OnpclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcr", DbType="NVarChar(50)")]
		public string pcr
		{
			get
			{
				return this._pcr;
			}
			set
			{
				if ((this._pcr != value))
				{
					this.OnpcrChanging(value);
					this.SendPropertyChanging();
					this._pcr = value;
					this.SendPropertyChanged("pcr");
					this.OnpcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ls", DbType="NVarChar(50)")]
		public string ls
		{
			get
			{
				return this._ls;
			}
			set
			{
				if ((this._ls != value))
				{
					this.OnlsChanging(value);
					this.SendPropertyChanging();
					this._ls = value;
					this.SendPropertyChanged("ls");
					this.OnlsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cwl", DbType="NVarChar(50)")]
		public string cwl
		{
			get
			{
				return this._cwl;
			}
			set
			{
				if ((this._cwl != value))
				{
					this.OncwlChanging(value);
					this.SendPropertyChanging();
					this._cwl = value;
					this.SendPropertyChanged("cwl");
					this.OncwlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cwr", DbType="NVarChar(50)")]
		public string cwr
		{
			get
			{
				return this._cwr;
			}
			set
			{
				if ((this._cwr != value))
				{
					this.OncwrChanging(value);
					this.SendPropertyChanging();
					this._cwr = value;
					this.SendPropertyChanged("cwr");
					this.OncwrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mh", DbType="NVarChar(50)")]
		public string mh
		{
			get
			{
				return this._mh;
			}
			set
			{
				if ((this._mh != value))
				{
					this.OnmhChanging(value);
					this.SendPropertyChanging();
					this._mh = value;
					this.SendPropertyChanged("mh");
					this.OnmhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtl1", DbType="NVarChar(50)")]
		public string mtl1
		{
			get
			{
				return this._mtl1;
			}
			set
			{
				if ((this._mtl1 != value))
				{
					this.Onmtl1Changing(value);
					this.SendPropertyChanging();
					this._mtl1 = value;
					this.SendPropertyChanged("mtl1");
					this.Onmtl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtl2", DbType="NVarChar(50)")]
		public string mtl2
		{
			get
			{
				return this._mtl2;
			}
			set
			{
				if ((this._mtl2 != value))
				{
					this.Onmtl2Changing(value);
					this.SendPropertyChanging();
					this._mtl2 = value;
					this.SendPropertyChanged("mtl2");
					this.Onmtl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtl3", DbType="NVarChar(50)")]
		public string mtl3
		{
			get
			{
				return this._mtl3;
			}
			set
			{
				if ((this._mtl3 != value))
				{
					this.Onmtl3Changing(value);
					this.SendPropertyChanging();
					this._mtl3 = value;
					this.SendPropertyChanged("mtl3");
					this.Onmtl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtr1", DbType="NVarChar(50)")]
		public string mtr1
		{
			get
			{
				return this._mtr1;
			}
			set
			{
				if ((this._mtr1 != value))
				{
					this.Onmtr1Changing(value);
					this.SendPropertyChanging();
					this._mtr1 = value;
					this.SendPropertyChanged("mtr1");
					this.Onmtr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtr2", DbType="NVarChar(50)")]
		public string mtr2
		{
			get
			{
				return this._mtr2;
			}
			set
			{
				if ((this._mtr2 != value))
				{
					this.Onmtr2Changing(value);
					this.SendPropertyChanging();
					this._mtr2 = value;
					this.SendPropertyChanged("mtr2");
					this.Onmtr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtr3", DbType="NVarChar(50)")]
		public string mtr3
		{
			get
			{
				return this._mtr3;
			}
			set
			{
				if ((this._mtr3 != value))
				{
					this.Onmtr3Changing(value);
					this.SendPropertyChanging();
					this._mtr3 = value;
					this.SendPropertyChanged("mtr3");
					this.Onmtr3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnl1", DbType="NVarChar(50)")]
		public string mnl1
		{
			get
			{
				return this._mnl1;
			}
			set
			{
				if ((this._mnl1 != value))
				{
					this.Onmnl1Changing(value);
					this.SendPropertyChanging();
					this._mnl1 = value;
					this.SendPropertyChanged("mnl1");
					this.Onmnl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnl2", DbType="NVarChar(50)")]
		public string mnl2
		{
			get
			{
				return this._mnl2;
			}
			set
			{
				if ((this._mnl2 != value))
				{
					this.Onmnl2Changing(value);
					this.SendPropertyChanging();
					this._mnl2 = value;
					this.SendPropertyChanged("mnl2");
					this.Onmnl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnl3", DbType="NVarChar(50)")]
		public string mnl3
		{
			get
			{
				return this._mnl3;
			}
			set
			{
				if ((this._mnl3 != value))
				{
					this.Onmnl3Changing(value);
					this.SendPropertyChanging();
					this._mnl3 = value;
					this.SendPropertyChanged("mnl3");
					this.Onmnl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnr1", DbType="NVarChar(50)")]
		public string mnr1
		{
			get
			{
				return this._mnr1;
			}
			set
			{
				if ((this._mnr1 != value))
				{
					this.Onmnr1Changing(value);
					this.SendPropertyChanging();
					this._mnr1 = value;
					this.SendPropertyChanged("mnr1");
					this.Onmnr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnr2", DbType="NVarChar(50)")]
		public string mnr2
		{
			get
			{
				return this._mnr2;
			}
			set
			{
				if ((this._mnr2 != value))
				{
					this.Onmnr2Changing(value);
					this.SendPropertyChanging();
					this._mnr2 = value;
					this.SendPropertyChanged("mnr2");
					this.Onmnr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnr3", DbType="NVarChar(50)")]
		public string mnr3
		{
			get
			{
				return this._mnr3;
			}
			set
			{
				if ((this._mnr3 != value))
				{
					this.Onmnr3Changing(value);
					this.SendPropertyChanging();
					this._mnr3 = value;
					this.SendPropertyChanged("mnr3");
					this.Onmnr3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtl1", DbType="NVarChar(50)")]
		public string rtl1
		{
			get
			{
				return this._rtl1;
			}
			set
			{
				if ((this._rtl1 != value))
				{
					this.Onrtl1Changing(value);
					this.SendPropertyChanging();
					this._rtl1 = value;
					this.SendPropertyChanged("rtl1");
					this.Onrtl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtl2", DbType="NVarChar(50)")]
		public string rtl2
		{
			get
			{
				return this._rtl2;
			}
			set
			{
				if ((this._rtl2 != value))
				{
					this.Onrtl2Changing(value);
					this.SendPropertyChanging();
					this._rtl2 = value;
					this.SendPropertyChanged("rtl2");
					this.Onrtl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtl3", DbType="NVarChar(50)")]
		public string rtl3
		{
			get
			{
				return this._rtl3;
			}
			set
			{
				if ((this._rtl3 != value))
				{
					this.Onrtl3Changing(value);
					this.SendPropertyChanging();
					this._rtl3 = value;
					this.SendPropertyChanged("rtl3");
					this.Onrtl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnl1", DbType="NVarChar(50)")]
		public string rnl1
		{
			get
			{
				return this._rnl1;
			}
			set
			{
				if ((this._rnl1 != value))
				{
					this.Onrnl1Changing(value);
					this.SendPropertyChanging();
					this._rnl1 = value;
					this.SendPropertyChanged("rnl1");
					this.Onrnl1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnl2", DbType="NVarChar(50)")]
		public string rnl2
		{
			get
			{
				return this._rnl2;
			}
			set
			{
				if ((this._rnl2 != value))
				{
					this.Onrnl2Changing(value);
					this.SendPropertyChanging();
					this._rnl2 = value;
					this.SendPropertyChanged("rnl2");
					this.Onrnl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnl3", DbType="NVarChar(50)")]
		public string rnl3
		{
			get
			{
				return this._rnl3;
			}
			set
			{
				if ((this._rnl3 != value))
				{
					this.Onrnl3Changing(value);
					this.SendPropertyChanging();
					this._rnl3 = value;
					this.SendPropertyChanged("rnl3");
					this.Onrnl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtr1", DbType="NVarChar(50)")]
		public string rtr1
		{
			get
			{
				return this._rtr1;
			}
			set
			{
				if ((this._rtr1 != value))
				{
					this.Onrtr1Changing(value);
					this.SendPropertyChanging();
					this._rtr1 = value;
					this.SendPropertyChanged("rtr1");
					this.Onrtr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtr2", DbType="NVarChar(50)")]
		public string rtr2
		{
			get
			{
				return this._rtr2;
			}
			set
			{
				if ((this._rtr2 != value))
				{
					this.Onrtr2Changing(value);
					this.SendPropertyChanging();
					this._rtr2 = value;
					this.SendPropertyChanged("rtr2");
					this.Onrtr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtr3", DbType="NVarChar(50)")]
		public string rtr3
		{
			get
			{
				return this._rtr3;
			}
			set
			{
				if ((this._rtr3 != value))
				{
					this.Onrtr3Changing(value);
					this.SendPropertyChanging();
					this._rtr3 = value;
					this.SendPropertyChanged("rtr3");
					this.Onrtr3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnr1", DbType="NVarChar(50)")]
		public string rnr1
		{
			get
			{
				return this._rnr1;
			}
			set
			{
				if ((this._rnr1 != value))
				{
					this.Onrnr1Changing(value);
					this.SendPropertyChanging();
					this._rnr1 = value;
					this.SendPropertyChanged("rnr1");
					this.Onrnr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnr2", DbType="NVarChar(50)")]
		public string rnr2
		{
			get
			{
				return this._rnr2;
			}
			set
			{
				if ((this._rnr2 != value))
				{
					this.Onrnr2Changing(value);
					this.SendPropertyChanging();
					this._rnr2 = value;
					this.SendPropertyChanged("rnr2");
					this.Onrnr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnr3", DbType="NVarChar(50)")]
		public string rnr3
		{
			get
			{
				return this._rnr3;
			}
			set
			{
				if ((this._rnr3 != value))
				{
					this.Onrnr3Changing(value);
					this.SendPropertyChanging();
					this._rnr3 = value;
					this.SendPropertyChanged("rnr3");
					this.Onrnr3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtl", DbType="NVarChar(50)")]
		public string sdtl
		{
			get
			{
				return this._sdtl;
			}
			set
			{
				if ((this._sdtl != value))
				{
					this.OnsdtlChanging(value);
					this.SendPropertyChanging();
					this._sdtl = value;
					this.SendPropertyChanged("sdtl");
					this.OnsdtlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtr", DbType="NVarChar(50)")]
		public string sdtr
		{
			get
			{
				return this._sdtr;
			}
			set
			{
				if ((this._sdtr != value))
				{
					this.OnsdtrChanging(value);
					this.SendPropertyChanging();
					this._sdtr = value;
					this.SendPropertyChanged("sdtr");
					this.OnsdtrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdnl", DbType="NVarChar(50)")]
		public string sdnl
		{
			get
			{
				return this._sdnl;
			}
			set
			{
				if ((this._sdnl != value))
				{
					this.OnsdnlChanging(value);
					this.SendPropertyChanging();
					this._sdnl = value;
					this.SendPropertyChanged("sdnl");
					this.OnsdnlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdnr", DbType="NVarChar(50)")]
		public string sdnr
		{
			get
			{
				return this._sdnr;
			}
			set
			{
				if ((this._sdnr != value))
				{
					this.OnsdnrChanging(value);
					this.SendPropertyChanging();
					this._sdnr = value;
					this.SendPropertyChanged("sdnr");
					this.OnsdnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_olt", DbType="NVarChar(50)")]
		public string olt
		{
			get
			{
				return this._olt;
			}
			set
			{
				if ((this._olt != value))
				{
					this.OnoltChanging(value);
					this.SendPropertyChanging();
					this._olt = value;
					this.SendPropertyChanged("olt");
					this.OnoltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oln", DbType="NVarChar(50)")]
		public string oln
		{
			get
			{
				return this._oln;
			}
			set
			{
				if ((this._oln != value))
				{
					this.OnolnChanging(value);
					this.SendPropertyChanging();
					this._oln = value;
					this.SendPropertyChanged("oln");
					this.OnolnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oln2", DbType="NVarChar(50)")]
		public string oln2
		{
			get
			{
				return this._oln2;
			}
			set
			{
				if ((this._oln2 != value))
				{
					this.Onoln2Changing(value);
					this.SendPropertyChanging();
					this._oln2 = value;
					this.SendPropertyChanged("oln2");
					this.Onoln2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp1", DbType="NVarChar(50)")]
		public string sp1
		{
			get
			{
				return this._sp1;
			}
			set
			{
				if ((this._sp1 != value))
				{
					this.Onsp1Changing(value);
					this.SendPropertyChanging();
					this._sp1 = value;
					this.SendPropertyChanged("sp1");
					this.Onsp1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp2", DbType="NVarChar(50)")]
		public string sp2
		{
			get
			{
				return this._sp2;
			}
			set
			{
				if ((this._sp2 != value))
				{
					this.Onsp2Changing(value);
					this.SendPropertyChanging();
					this._sp2 = value;
					this.SendPropertyChanged("sp2");
					this.Onsp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y", DbType="NVarChar(50)")]
		public string y
		{
			get
			{
				return this._y;
			}
			set
			{
				if ((this._y != value))
				{
					this.OnyChanging(value);
					this.SendPropertyChanging();
					this._y = value;
					this.SendPropertyChanged("y");
					this.OnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m", DbType="NVarChar(50)")]
		public string m
		{
			get
			{
				return this._m;
			}
			set
			{
				if ((this._m != value))
				{
					this.OnmChanging(value);
					this.SendPropertyChanging();
					this._m = value;
					this.SendPropertyChanged("m");
					this.OnmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="NVarChar(50)")]
		public string d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this.OndChanging(value);
					this.SendPropertyChanging();
					this._d = value;
					this.SendPropertyChanged("d");
					this.OndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbd", DbType="NVarChar(255)")]
		public string cbd
		{
			get
			{
				return this._cbd;
			}
			set
			{
				if ((this._cbd != value))
				{
					this.OncbdChanging(value);
					this.SendPropertyChanging();
					this._cbd = value;
					this.SendPropertyChanged("cbd");
					this.OncbdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cc_ctc")]
	public partial class cc_ctc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _uname;
		
		private string _ContractNO;
		
		private System.Nullable<System.DateTime> _fhtime;
		
		private System.Nullable<int> _fy;
		
		private System.Nullable<int> _fm;
		
		private System.Nullable<int> _fd;
		
		private string _mln;
		
		private string _name;
		
		private string _type;
		
		private string _sn;
		
		private string _pn;
		
		private string _pc;
		
		private string _cw;
		
		private string _rhm;
		
		private string _mhc;
		
		private string _mrc;
		
		private string _minmaxwr;
		
		private string _cbw;
		
		private string _cjbw;
		
		private string _sh;
		
		private string _maxah;
		
		private string _hs;
		
		private string _ts;
		
		private string _ss;
		
		private string _hwt;
		
		private string _hwn;
		
		private string _twt;
		
		private string _twn;
		
		private string _sgt;
		
		private string _sgn;
		
		private string _cmt;
		
		private string _cmn;
		
		private string _lcot;
		
		private string _lcon;
		
		private string _mcot;
		
		private string _mcon;
		
		private string _y;
		
		private string _m;
		
		private string _d;
		
		private string _hr;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OnContractNOChanging(string value);
    partial void OnContractNOChanged();
    partial void OnfhtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnfhtimeChanged();
    partial void OnfyChanging(System.Nullable<int> value);
    partial void OnfyChanged();
    partial void OnfmChanging(System.Nullable<int> value);
    partial void OnfmChanged();
    partial void OnfdChanging(System.Nullable<int> value);
    partial void OnfdChanged();
    partial void OnmlnChanging(string value);
    partial void OnmlnChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnsnChanging(string value);
    partial void OnsnChanged();
    partial void OnpnChanging(string value);
    partial void OnpnChanged();
    partial void OnpcChanging(string value);
    partial void OnpcChanged();
    partial void OncwChanging(string value);
    partial void OncwChanged();
    partial void OnrhmChanging(string value);
    partial void OnrhmChanged();
    partial void OnmhcChanging(string value);
    partial void OnmhcChanged();
    partial void OnmrcChanging(string value);
    partial void OnmrcChanged();
    partial void OnminmaxwrChanging(string value);
    partial void OnminmaxwrChanged();
    partial void OncbwChanging(string value);
    partial void OncbwChanged();
    partial void OncjbwChanging(string value);
    partial void OncjbwChanged();
    partial void OnshChanging(string value);
    partial void OnshChanged();
    partial void OnmaxahChanging(string value);
    partial void OnmaxahChanged();
    partial void OnhsChanging(string value);
    partial void OnhsChanged();
    partial void OntsChanging(string value);
    partial void OntsChanged();
    partial void OnssChanging(string value);
    partial void OnssChanged();
    partial void OnhwtChanging(string value);
    partial void OnhwtChanged();
    partial void OnhwnChanging(string value);
    partial void OnhwnChanged();
    partial void OntwtChanging(string value);
    partial void OntwtChanged();
    partial void OntwnChanging(string value);
    partial void OntwnChanged();
    partial void OnsgtChanging(string value);
    partial void OnsgtChanged();
    partial void OnsgnChanging(string value);
    partial void OnsgnChanged();
    partial void OncmtChanging(string value);
    partial void OncmtChanged();
    partial void OncmnChanging(string value);
    partial void OncmnChanged();
    partial void OnlcotChanging(string value);
    partial void OnlcotChanged();
    partial void OnlconChanging(string value);
    partial void OnlconChanged();
    partial void OnmcotChanging(string value);
    partial void OnmcotChanged();
    partial void OnmconChanging(string value);
    partial void OnmconChanged();
    partial void OnyChanging(string value);
    partial void OnyChanged();
    partial void OnmChanging(string value);
    partial void OnmChanged();
    partial void OndChanging(string value);
    partial void OndChanged();
    partial void OnhrChanging(string value);
    partial void OnhrChanged();
    #endregion
		
		public cc_ctc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="NVarChar(50)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this.OnunameChanging(value);
					this.SendPropertyChanging();
					this._uname = value;
					this.SendPropertyChanged("uname");
					this.OnunameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNO", DbType="NVarChar(50)")]
		public string ContractNO
		{
			get
			{
				return this._ContractNO;
			}
			set
			{
				if ((this._ContractNO != value))
				{
					this.OnContractNOChanging(value);
					this.SendPropertyChanging();
					this._ContractNO = value;
					this.SendPropertyChanged("ContractNO");
					this.OnContractNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fhtime", DbType="Date")]
		public System.Nullable<System.DateTime> fhtime
		{
			get
			{
				return this._fhtime;
			}
			set
			{
				if ((this._fhtime != value))
				{
					this.OnfhtimeChanging(value);
					this.SendPropertyChanging();
					this._fhtime = value;
					this.SendPropertyChanged("fhtime");
					this.OnfhtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fy", DbType="Int")]
		public System.Nullable<int> fy
		{
			get
			{
				return this._fy;
			}
			set
			{
				if ((this._fy != value))
				{
					this.OnfyChanging(value);
					this.SendPropertyChanging();
					this._fy = value;
					this.SendPropertyChanged("fy");
					this.OnfyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fm", DbType="Int")]
		public System.Nullable<int> fm
		{
			get
			{
				return this._fm;
			}
			set
			{
				if ((this._fm != value))
				{
					this.OnfmChanging(value);
					this.SendPropertyChanging();
					this._fm = value;
					this.SendPropertyChanged("fm");
					this.OnfmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fd", DbType="Int")]
		public System.Nullable<int> fd
		{
			get
			{
				return this._fd;
			}
			set
			{
				if ((this._fd != value))
				{
					this.OnfdChanging(value);
					this.SendPropertyChanging();
					this._fd = value;
					this.SendPropertyChanged("fd");
					this.OnfdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mln", DbType="NVarChar(50)")]
		public string mln
		{
			get
			{
				return this._mln;
			}
			set
			{
				if ((this._mln != value))
				{
					this.OnmlnChanging(value);
					this.SendPropertyChanging();
					this._mln = value;
					this.SendPropertyChanged("mln");
					this.OnmlnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn", DbType="NVarChar(50)")]
		public string sn
		{
			get
			{
				return this._sn;
			}
			set
			{
				if ((this._sn != value))
				{
					this.OnsnChanging(value);
					this.SendPropertyChanging();
					this._sn = value;
					this.SendPropertyChanged("sn");
					this.OnsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pn", DbType="NVarChar(50)")]
		public string pn
		{
			get
			{
				return this._pn;
			}
			set
			{
				if ((this._pn != value))
				{
					this.OnpnChanging(value);
					this.SendPropertyChanging();
					this._pn = value;
					this.SendPropertyChanged("pn");
					this.OnpnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pc", DbType="NVarChar(50)")]
		public string pc
		{
			get
			{
				return this._pc;
			}
			set
			{
				if ((this._pc != value))
				{
					this.OnpcChanging(value);
					this.SendPropertyChanging();
					this._pc = value;
					this.SendPropertyChanged("pc");
					this.OnpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cw", DbType="NVarChar(50)")]
		public string cw
		{
			get
			{
				return this._cw;
			}
			set
			{
				if ((this._cw != value))
				{
					this.OncwChanging(value);
					this.SendPropertyChanging();
					this._cw = value;
					this.SendPropertyChanged("cw");
					this.OncwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rhm", DbType="NVarChar(50)")]
		public string rhm
		{
			get
			{
				return this._rhm;
			}
			set
			{
				if ((this._rhm != value))
				{
					this.OnrhmChanging(value);
					this.SendPropertyChanging();
					this._rhm = value;
					this.SendPropertyChanged("rhm");
					this.OnrhmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mhc", DbType="NVarChar(50)")]
		public string mhc
		{
			get
			{
				return this._mhc;
			}
			set
			{
				if ((this._mhc != value))
				{
					this.OnmhcChanging(value);
					this.SendPropertyChanging();
					this._mhc = value;
					this.SendPropertyChanged("mhc");
					this.OnmhcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mrc", DbType="NVarChar(50)")]
		public string mrc
		{
			get
			{
				return this._mrc;
			}
			set
			{
				if ((this._mrc != value))
				{
					this.OnmrcChanging(value);
					this.SendPropertyChanging();
					this._mrc = value;
					this.SendPropertyChanged("mrc");
					this.OnmrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minmaxwr", DbType="NVarChar(50)")]
		public string minmaxwr
		{
			get
			{
				return this._minmaxwr;
			}
			set
			{
				if ((this._minmaxwr != value))
				{
					this.OnminmaxwrChanging(value);
					this.SendPropertyChanging();
					this._minmaxwr = value;
					this.SendPropertyChanged("minmaxwr");
					this.OnminmaxwrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbw", DbType="NVarChar(50)")]
		public string cbw
		{
			get
			{
				return this._cbw;
			}
			set
			{
				if ((this._cbw != value))
				{
					this.OncbwChanging(value);
					this.SendPropertyChanging();
					this._cbw = value;
					this.SendPropertyChanged("cbw");
					this.OncbwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cjbw", DbType="NVarChar(50)")]
		public string cjbw
		{
			get
			{
				return this._cjbw;
			}
			set
			{
				if ((this._cjbw != value))
				{
					this.OncjbwChanging(value);
					this.SendPropertyChanging();
					this._cjbw = value;
					this.SendPropertyChanged("cjbw");
					this.OncjbwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh", DbType="NVarChar(50)")]
		public string sh
		{
			get
			{
				return this._sh;
			}
			set
			{
				if ((this._sh != value))
				{
					this.OnshChanging(value);
					this.SendPropertyChanging();
					this._sh = value;
					this.SendPropertyChanged("sh");
					this.OnshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxah", DbType="NVarChar(50)")]
		public string maxah
		{
			get
			{
				return this._maxah;
			}
			set
			{
				if ((this._maxah != value))
				{
					this.OnmaxahChanging(value);
					this.SendPropertyChanging();
					this._maxah = value;
					this.SendPropertyChanged("maxah");
					this.OnmaxahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hs", DbType="NVarChar(50)")]
		public string hs
		{
			get
			{
				return this._hs;
			}
			set
			{
				if ((this._hs != value))
				{
					this.OnhsChanging(value);
					this.SendPropertyChanging();
					this._hs = value;
					this.SendPropertyChanged("hs");
					this.OnhsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="NVarChar(50)")]
		public string ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ss", DbType="NVarChar(50)")]
		public string ss
		{
			get
			{
				return this._ss;
			}
			set
			{
				if ((this._ss != value))
				{
					this.OnssChanging(value);
					this.SendPropertyChanging();
					this._ss = value;
					this.SendPropertyChanged("ss");
					this.OnssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hwt", DbType="NVarChar(50)")]
		public string hwt
		{
			get
			{
				return this._hwt;
			}
			set
			{
				if ((this._hwt != value))
				{
					this.OnhwtChanging(value);
					this.SendPropertyChanging();
					this._hwt = value;
					this.SendPropertyChanged("hwt");
					this.OnhwtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hwn", DbType="NVarChar(50)")]
		public string hwn
		{
			get
			{
				return this._hwn;
			}
			set
			{
				if ((this._hwn != value))
				{
					this.OnhwnChanging(value);
					this.SendPropertyChanging();
					this._hwn = value;
					this.SendPropertyChanged("hwn");
					this.OnhwnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twt", DbType="NVarChar(50)")]
		public string twt
		{
			get
			{
				return this._twt;
			}
			set
			{
				if ((this._twt != value))
				{
					this.OntwtChanging(value);
					this.SendPropertyChanging();
					this._twt = value;
					this.SendPropertyChanged("twt");
					this.OntwtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twn", DbType="NVarChar(50)")]
		public string twn
		{
			get
			{
				return this._twn;
			}
			set
			{
				if ((this._twn != value))
				{
					this.OntwnChanging(value);
					this.SendPropertyChanging();
					this._twn = value;
					this.SendPropertyChanged("twn");
					this.OntwnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sgt", DbType="NVarChar(50)")]
		public string sgt
		{
			get
			{
				return this._sgt;
			}
			set
			{
				if ((this._sgt != value))
				{
					this.OnsgtChanging(value);
					this.SendPropertyChanging();
					this._sgt = value;
					this.SendPropertyChanged("sgt");
					this.OnsgtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sgn", DbType="NVarChar(50)")]
		public string sgn
		{
			get
			{
				return this._sgn;
			}
			set
			{
				if ((this._sgn != value))
				{
					this.OnsgnChanging(value);
					this.SendPropertyChanging();
					this._sgn = value;
					this.SendPropertyChanged("sgn");
					this.OnsgnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmt", DbType="NVarChar(50)")]
		public string cmt
		{
			get
			{
				return this._cmt;
			}
			set
			{
				if ((this._cmt != value))
				{
					this.OncmtChanging(value);
					this.SendPropertyChanging();
					this._cmt = value;
					this.SendPropertyChanged("cmt");
					this.OncmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmn", DbType="NVarChar(50)")]
		public string cmn
		{
			get
			{
				return this._cmn;
			}
			set
			{
				if ((this._cmn != value))
				{
					this.OncmnChanging(value);
					this.SendPropertyChanging();
					this._cmn = value;
					this.SendPropertyChanged("cmn");
					this.OncmnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lcot", DbType="NVarChar(50)")]
		public string lcot
		{
			get
			{
				return this._lcot;
			}
			set
			{
				if ((this._lcot != value))
				{
					this.OnlcotChanging(value);
					this.SendPropertyChanging();
					this._lcot = value;
					this.SendPropertyChanged("lcot");
					this.OnlcotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lcon", DbType="NVarChar(50)")]
		public string lcon
		{
			get
			{
				return this._lcon;
			}
			set
			{
				if ((this._lcon != value))
				{
					this.OnlconChanging(value);
					this.SendPropertyChanging();
					this._lcon = value;
					this.SendPropertyChanged("lcon");
					this.OnlconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mcot", DbType="NVarChar(50)")]
		public string mcot
		{
			get
			{
				return this._mcot;
			}
			set
			{
				if ((this._mcot != value))
				{
					this.OnmcotChanging(value);
					this.SendPropertyChanging();
					this._mcot = value;
					this.SendPropertyChanged("mcot");
					this.OnmcotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mcon", DbType="NVarChar(50)")]
		public string mcon
		{
			get
			{
				return this._mcon;
			}
			set
			{
				if ((this._mcon != value))
				{
					this.OnmconChanging(value);
					this.SendPropertyChanging();
					this._mcon = value;
					this.SendPropertyChanged("mcon");
					this.OnmconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_y", DbType="NVarChar(50)")]
		public string y
		{
			get
			{
				return this._y;
			}
			set
			{
				if ((this._y != value))
				{
					this.OnyChanging(value);
					this.SendPropertyChanging();
					this._y = value;
					this.SendPropertyChanged("y");
					this.OnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m", DbType="NVarChar(50)")]
		public string m
		{
			get
			{
				return this._m;
			}
			set
			{
				if ((this._m != value))
				{
					this.OnmChanging(value);
					this.SendPropertyChanging();
					this._m = value;
					this.SendPropertyChanged("m");
					this.OnmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="NVarChar(50)")]
		public string d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this.OndChanging(value);
					this.SendPropertyChanging();
					this._d = value;
					this.SendPropertyChanged("d");
					this.OndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr", DbType="NVarChar(MAX)")]
		public string hr
		{
			get
			{
				return this._hr;
			}
			set
			{
				if ((this._hr != value))
				{
					this.OnhrChanging(value);
					this.SendPropertyChanging();
					this._hr = value;
					this.SendPropertyChanged("hr");
					this.OnhrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.catalog")]
	public partial class catalog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _catID;
		
		private string _catName;
		
		private System.Nullable<int> _catOrder;
		
		private System.Nullable<int> _parentID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncatIDChanging(int value);
    partial void OncatIDChanged();
    partial void OncatNameChanging(string value);
    partial void OncatNameChanged();
    partial void OncatOrderChanging(System.Nullable<int> value);
    partial void OncatOrderChanged();
    partial void OnparentIDChanging(System.Nullable<int> value);
    partial void OnparentIDChanged();
    #endregion
		
		public catalog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int catID
		{
			get
			{
				return this._catID;
			}
			set
			{
				if ((this._catID != value))
				{
					this.OncatIDChanging(value);
					this.SendPropertyChanging();
					this._catID = value;
					this.SendPropertyChanged("catID");
					this.OncatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catName", DbType="NVarChar(255)")]
		public string catName
		{
			get
			{
				return this._catName;
			}
			set
			{
				if ((this._catName != value))
				{
					this.OncatNameChanging(value);
					this.SendPropertyChanging();
					this._catName = value;
					this.SendPropertyChanged("catName");
					this.OncatNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catOrder", DbType="Int")]
		public System.Nullable<int> catOrder
		{
			get
			{
				return this._catOrder;
			}
			set
			{
				if ((this._catOrder != value))
				{
					this.OncatOrderChanging(value);
					this.SendPropertyChanging();
					this._catOrder = value;
					this.SendPropertyChanged("catOrder");
					this.OncatOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentID", DbType="Int")]
		public System.Nullable<int> parentID
		{
			get
			{
				return this._parentID;
			}
			set
			{
				if ((this._parentID != value))
				{
					this.OnparentIDChanging(value);
					this.SendPropertyChanging();
					this._parentID = value;
					this.SendPropertyChanged("parentID");
					this.OnparentIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
